# Generated by Django 4.1.6 on 2023-02-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='servings_time',
            new_name='servings',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='servings_time_unit',
            new_name='servings_unit',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
